### ISSUE TITLE
General JupyterHub repo maintenance

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/nativeauthenticator#133]
I wanted to refresh some parts of this repo to be better in sync with other JupyterHub repo's for easier maintenance and a more consistent experience.

- [x] Migrate CircleCI to GitHub actions #134
- [x] Add README badges #135
  - [x] GitHub workflow tests
  - [x] PyPI: https://pypi.org/project/jupyterhub-nativeauthenticator/
  - [x] ReadTheDocs build status
  - [x] Forum / social / issues
- [x] Add github tags retrospectively on commits for when releases were made
  I went ahead and pushed tags matching the release datetime's in PyPI
- [x] Update CHANGELOG.md with github-activity #137 
- [x] Setup release automation GitHub workflows
  - [x] Add github workflow #136
  - [x] PyPI maintainers: @leportella @lambdaTotoro, could you add me and the user named `jupyterhub-bot` as a maintainer to https://pypi.org/project/jupyterhub-nativeauthenticator/? I'd like to create a publishing password for the release automation and figure it is also good to have some more people available to maintain the project.
  - [x] Add github project secret `PYPI_PASSWORD` using deployment token created by jupyterhub-bot at PyPI
- [x] Provide PR preview of documentation at readthedocs
  - [x] More than one RTD admin: @leportella could I be added as a admin of https://readthedocs.org/projects/native-authenticator/? Perhaps also @lambdaTotoro if that is okay with you Jonas?
  - [x] Activate PR previews in RTD project settings

**Comment by consideRatio** [comment]
@leportella could you also add me as an admin to https://readthedocs.org/projects/native-authenticator/?

**Comment by consideRatio** [comment]
Thanks @lambdaTotoro and @leportella!
