### ISSUE TITLE
Roadmap to 1.0 Release

### ISSUE THREAD

**Issue by lambdaTotoro** [jupyterhub/nativeauthenticator#149]
I've been talking with @consideRatio about moving this project forward.
Here's what I think would need to happen for me to be happy to call it `1.0`, roughly in order of (estimated) difficulty.

### Roadmap

- [x] Fix error message for unauthorised logins (see #119)
~~- [ ] Log in users directly after sign-up, if there's no need for authorisation. (#72)~~
- [x] Merge #79 and implement the suggestions in #127 
- [x] Sort out the system user generation around Issue #105 
- [x] Review / correct / merge Pull Requests #145, #146 and #148 by @davidedelvento

After all of that is done:

- [x] Bring the documentation up to spec with all new features
~~- [ ] We're getting a lot of issues in the context of TLJ and Docker, I'd like to have a tried-and-tested config available for that.~~

But if anyone else (especially @leportella, @consideRatio and @yuvipanda) have more ideas or any form of input, I'll be very happy to hear it.

**Comment by yuvipanda** [comment]
<3 to see the authenticator being pushed forward. THANK YOU, @lambdaTotoro :)

**Comment by consideRatio** [comment]
> <3 to see the authenticator being pushed forward. THANK YOU, @lambdaTotoro :)

Mee too!!! Thank you @lambdaTotoro!!

I'll try contribute to the review process of the PRs, feel free to ping me about anything regarding this repo's maintenance @lambdaTotoro!
